<a href="https://colab.research.google.com/github/faisu6339-glitch/Deep-Learning/blob/main/ANN_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is an ANN (Artificial Neural Network)?

An Artificial Neural Network (ANN) is a computational model inspired by the structure and function of biological neural networks (like the human brain). ANNs are designed to recognize patterns, process data, and make decisions in a way similar to how humans learn.

### 1. Basic Structure

An ANN is composed of multiple layers of interconnected **neurons** (also called nodes). These layers typically include:

*   **Input Layer:** This layer receives the initial data. Each neuron in the input layer corresponds to an input feature.
*   **Hidden Layers:** One or more layers between the input and output layers. These layers perform computations and feature extraction from the input data. The number of hidden layers and neurons within them can vary greatly depending on the complexity of the problem.
*   **Output Layer:** This layer produces the final result of the network. The number of neurons in the output layer depends on the type of problem (e.g., one neuron for binary classification, multiple neurons for multi-class classification or regression).

### 2. Neurons (Nodes)

Each neuron in an ANN is a fundamental processing unit. It performs two main operations:

*   **Weighted Sum:** It takes inputs from previous neurons, multiplies each input by a corresponding **weight**, and then sums these weighted inputs. A **bias** term is often added to this sum.
    *   `Z = (Input1 * Weight1) + (Input2 * Weight2) + ... + Bias`
*   **Activation Function:** The weighted sum `Z` is then passed through an **activation function**. This function introduces non-linearity into the network, allowing it to learn complex patterns. Common activation functions include ReLU (Rectified Linear Unit), Sigmoid, and Tanh.
    *   `Output = Activation_Function(Z)`

### 3. Weights and Biases

*   **Weights:** These are numerical values that determine the strength of the connection between neurons. During the learning process, the network adjusts these weights to minimize errors. A higher weight means a stronger influence of one neuron's output on the next.
*   **Biases:** These are constant values added to the weighted sum. They allow the activation function to be shifted, providing more flexibility for the model to fit the data.

### 4. Learning Process (Training)

ANNs learn from data through a process called **training**, which typically involves:

*   **Forward Propagation:** Input data is fed into the network, processed through the hidden layers, and an output is generated.
*   **Loss Function (Cost Function):** This function measures the difference between the network's predicted output and the actual (true) output. The goal is to minimize this loss.
*   **Backpropagation:** This is the core algorithm for training ANNs. It calculates the gradient of the loss function with respect to each weight and bias in the network. This gradient indicates how much each weight and bias contributed to the error.
*   **Optimizer (e.g., Gradient Descent):** An optimizer uses the gradients calculated by backpropagation to adjust the weights and biases in the direction that reduces the loss. This iterative process continues until the network's performance is satisfactory.

### 5. Types of ANNs

There are various architectures of ANNs, each suited for different types of problems:

*   **Feedforward Neural Networks (FNNs):** The simplest type, where information flows in only one direction from input to output, without loops.
*   **Recurrent Neural Networks (RNNs):** Designed for sequential data (like text or time series), they have connections that allow information to flow backward, giving them memory.
*   **Convolutional Neural Networks (CNNs):** Primarily used for image and video processing, they employ convolutional layers to automatically learn spatial hierarchies of features.
*   **Generative Adversarial Networks (GANs):** Consist of two competing neural networks (a generator and a discriminator) that learn to generate new, realistic data.
*   **Transformers:** A more recent architecture, highly effective for natural language processing tasks, utilizing self-attention mechanisms.

### 6. Applications

ANNs are at the heart of many modern AI applications, including:

*   **Image Recognition:** Facial recognition, object detection.
*   **Natural Language Processing (NLP):** Machine translation, sentiment analysis, chatbots.
*   **Speech Recognition:** Voice assistants.
*   **Recommendation Systems:** Personalizing content on streaming services or e-commerce sites.
*   **Medical Diagnosis:** Identifying diseases from medical images.
*   **Financial Forecasting:** Predicting stock prices or market trends.

In essence, ANNs are powerful tools capable of learning complex relationships within data, making them highly versatile for solving a wide range of challenging problems in artificial intelligence.

## Mathematical Working of ANN

To truly understand Artificial Neural Networks (ANNs), it's crucial to delve into the mathematical operations that power them. At its core, an ANN is a series of matrix multiplications and non-linear transformations.

### 1. Neuron's Mathematical Model

Each neuron in an ANN acts as a simple processing unit. For a single neuron, the process can be described in two steps:

*   **Weighted Sum (Linear Combination):** The neuron receives inputs (from the input layer or preceding hidden layer neurons), multiplies each input by a corresponding weight, and sums these products. A bias term is then added to this sum.
    If `x = [x1, x2, ..., xn]` is the input vector, `w = [w1, w2, ..., wn]` is the weight vector, and `b` is the bias, then the weighted sum `Z` is calculated as:

    $$Z = \sum_{i=1}^{n} (x_i \cdot w_i) + b = \mathbf{x}^T \mathbf{w} + b$$

    In a vectorized form, for a layer with `m` neurons, `W` would be a matrix of weights and `b` a vector of biases.

*   **Activation Function:** The weighted sum `Z` is then passed through an activation function, denoted as `f`, which introduces non-linearity. This non-linearity is vital; without it, an ANN would simply be a linear model, incapable of learning complex patterns.

    $$A = f(Z)$$

    Common activation functions include:
    *   **Sigmoid:** $f(Z) = \frac{1}{1 + e^{-Z}}$ (Outputs values between 0 and 1, often used in output layers for binary classification)
    *   **ReLU (Rectified Linear Unit):** $f(Z) = \max(0, Z)$ (Widely used in hidden layers due to computational efficiency and combating vanishing gradients)
    *   **Tanh (Hyperbolic Tangent):** $f(Z) = \frac{e^Z - e^{-Z}}{e^Z + e^{-Z}}$ (Outputs values between -1 and 1)

### 2. Forward Propagation

Forward propagation is the process of feeding input data through the network to produce an output. It involves applying the neuron's mathematical model layer by layer.

For a multi-layer network:

1.  **Input Layer:** The input features are directly passed to the first hidden layer.
2.  **Hidden Layers:** For each hidden layer `l`:
    *   Calculate the weighted sum for each neuron:
        $$Z^{[l]} = W^{[l]} A^{[l-1]} + b^{[l]}$$
        where $A^{[l-1]}$ is the activation from the previous layer, $W^{[l]}$ is the weight matrix for layer `l`, and $b^{[l]}$ is the bias vector for layer `l`.
    *   Apply the activation function:
        $$A^{[l]} = f^{[l]}(Z^{[l]})$$
3.  **Output Layer:** The final activation $A^{[L]}$ (where L is the number of layers) represents the network's prediction.

### 3. Loss Function (Cost Function)

The loss function quantifies the discrepancy between the network's predicted output ($\hat{y}$) and the true target output ($y$). The goal of training is to minimize this loss.

*   **Mean Squared Error (MSE):** For regression problems.
    $$L(y, \hat{y}) = \frac{1}{2} (y - \hat{y})^2$$
*   **Binary Cross-Entropy:** For binary classification problems.
    $$L(y, \hat{y}) = - (y \log(\hat{y}) + (1-y) \log(1-\hat{y}))$$
*   **Categorical Cross-Entropy:** For multi-class classification problems.
    $$L(y, \hat{y}) = - \sum_{i=1}^{C} y_i \log(\hat{y}_i)$$

The overall cost function `J` for a dataset of `m` examples is typically the average loss over all examples:

$$J(W, b) = \frac{1}{m} \sum_{j=1}^{m} L(y^{(j)}, \hat{y}^{(j)})$$

### 4. Backpropagation and Gradient Descent

Backpropagation is an algorithm used to efficiently compute the gradients of the loss function with respect to the weights and biases of the network. These gradients tell us how much each weight and bias contributes to the overall error.

**Gradient Descent** is the optimization algorithm that uses these gradients to iteratively adjust the weights and biases to minimize the loss function.

1.  **Initialize Parameters:** Start with random weights and biases.
2.  **Forward Pass:** Compute the output $\hat{y}$ and the loss $L$ for a given input $x$.
3.  **Backward Pass (Backpropagation):** Calculate the gradients $\frac{\partial L}{\partial W^{[l]}}$ and $\frac{\partial L}{\partial b^{[l]}}$ for each layer `l`, using the chain rule of calculus. This process starts from the output layer and works backward through the network.
    *   **Chain Rule Example:** For a simple neuron, $\frac{\partial L}{\partial w_i} = \frac{\partial L}{\partial A} \cdot \frac{\partial A}{\partial Z} \cdot \frac{\partial Z}{\partial w_i}$
        *   $\frac{\partial L}{\partial A}$: How much the loss changes with respect to the neuron's output.
        *   $\frac{\partial A}{\partial Z}$: The derivative of the activation function (e.g., for sigmoid, $f'(Z) = A(1-A)$).
        *   $\frac{\partial Z}{\partial w_i}$: How much the weighted sum changes with respect to the weight $w_i$ (which is $x_i$).

4.  **Update Parameters:** Adjust the weights and biases in the opposite direction of their gradients, scaled by a learning rate ($\alpha$).
    $$W^{[l]} = W^{[l]} - \alpha \frac{\partial L}{\partial W^{[l]}}$$
    $$b^{[l]} = b^{[l]} - \alpha \frac{\partial L}{\partial b^{[l]}}$$

This iterative process of forward propagation, loss calculation, backpropagation, and parameter update is repeated for many epochs (passes over the entire dataset) until the network's performance converges or reaches a satisfactory level.

## 🔥 Activation Functions (Very Important)

An **activation function** is a crucial component within an artificial neuron. It determines whether a neuron should be activated or not, and what the output of the neuron should be, given its input. Without activation functions, an ANN would simply be a linear model, regardless of how many layers it has. Linear models can only learn linear relationships, which severely limits their ability to solve complex problems.

#### Why are Activation Functions Important?

1.  **Introduce Non-linearity:** This is their primary role. Real-world data is almost always non-linear. By introducing non-linearity, activation functions allow neural networks to learn and model complex, non-linear relationships between inputs and outputs. Without them, stacking multiple layers would still result in a single linear transformation.
2.  **Enable Learning Complex Patterns:** Because of non-linearity, ANNs can approximate any continuous function, given enough hidden units and appropriate activation functions (this is related to the Universal Approximation Theorem).
3.  **Control Output Range:** Some activation functions (like sigmoid and tanh) squish the neuron's output into a specific range, which can be useful for certain types of tasks (e.g., probability outputs in classification).
4.  **Help with Backpropagation:** Their derivatives are used in the backpropagation algorithm to calculate the gradients and update the weights and biases of the network.

#### How They Work

After a neuron computes the weighted sum of its inputs and adds a bias (`Z = WX + b`), this `Z` value is passed through an activation function `f`. The output of the activation function, `A = f(Z)`, then becomes the input to the next layer of neurons (or the final output of the network).

#### Common Types of Activation Functions:

1.  **Sigmoid (Logistic) Function**
    *   **Formula:** $f(Z) = \frac{1}{1 + e^{-Z}}$
    *   **Output Range:** $(0, 1)$
    *   **Use Cases:** Historically popular, especially in the output layer for binary classification problems where the output can be interpreted as a probability. It squashes values between 0 and 1.
    *   **Pros:** Smooth gradient, clear prediction for 0 or 1.
    *   **Cons:**
        *   **Vanishing Gradient Problem:** For very large positive or negative values of `Z`, the gradient of the sigmoid function becomes very small (close to zero). This can halt the learning process for neurons in earlier layers during backpropagation.
        *   **Outputs are not zero-centered:** This can make the gradients of the weights always positive or always negative, leading to zig-zagging optimization paths.
        *   Computationally expensive due to the `exp` function.

2.  **Tanh (Hyperbolic Tangent) Function**
    *   **Formula:** $f(Z) = \frac{e^Z - e^{-Z}}{e^Z + e^{-Z}}$
    *   **Output Range:** $(-1, 1)$
    *   **Use Cases:** Often preferred over sigmoid in hidden layers because its output is zero-centered, which helps in gradient calculation. It squashes values between -1 and 1.
    *   **Pros:** Zero-centered output, stronger gradients than sigmoid.
    *   **Cons:** Still suffers from the vanishing gradient problem for very large inputs.

3.  **ReLU (Rectified Linear Unit) Function**
    *   **Formula:** $f(Z) = \max(0, Z)$
    *   **Output Range:** $[0, \infty)$
    *   **Use Cases:** The most widely used activation function for hidden layers in deep learning models today. It's simple and computationally efficient.
    *   **Pros:**
        *   **Solves Vanishing Gradient Problem (partially):** For positive inputs, the gradient is always 1, preventing the vanishing gradient issue.
        *   **Computational Efficiency:** Very fast to compute (just a `max` operation).
        *   **Sparsity:** Can lead to sparse activations, meaning some neurons output 0, which can make the model more efficient.
    *   **Cons:**
        *   **Dying ReLU Problem:** If the weighted sum `Z` is consistently negative, the ReLU neuron will output 0 and its gradient will also be 0. This means the neuron will stop learning and effectively "die" (never activate for any data point). This is particularly problematic during training if a large learning rate pushes too many neurons into this state.

4.  **Leaky ReLU Function**
    *   **Formula:** $f(Z) = \max(0.01Z, Z)$ (or $f(Z) = \begin{cases} Z & \text{if } Z > 0 \\ \alpha Z & \text{if } Z \le 0 \end{cases}$ where $\alpha$ is a small positive constant, e.g., 0.01)
    *   **Output Range:** $(-\infty, \infty)$
    *   **Use Cases:** An attempt to solve the dying ReLU problem. It allows a small, non-zero gradient when the unit is not active.
    *   **Pros:** Addresses the dying ReLU problem, still computationally efficient.
    *   **Cons:** The parameter $\alpha$ (slope for negative values) is typically fixed and not learned.

5.  **PReLU (Parametric ReLU) Function**
    *   **Formula:** $f(Z) = \begin{cases} Z & \text{if } Z > 0 \\ \alpha Z & \text{if } Z \le 0 \end{cases}$ where $\alpha$ is a learned parameter.
    *   **Output Range:** $(-\infty, \infty)$
    *   **Use Cases:** Similar to Leaky ReLU, but with a trainable parameter $\alpha$ which can lead to better performance.
    *   **Pros:** Addresses dying ReLU, $\alpha$ is learned, allowing for more flexibility.

6.  **ELU (Exponential Linear Unit) Function**
    *   **Formula:** $f(Z) = \begin{cases} Z & \text{if } Z > 0 \\ \alpha (e^Z - 1) & \text{if } Z \le 0 \end{cases}$ (where $\alpha$ is a hyperparameter, often 1)
    *   **Output Range:** $(-\alpha, \infty)$
    *   **Use Cases:** Similar to ReLU but with a smooth negative part that drives mean activations closer to zero. This can lead to faster learning.
    *   **Pros:** Mitigates dying ReLU, provides negative values which push the mean activation closer to zero, making it similar to batch normalization.
    *   **Cons:** Computationally more expensive than ReLU/Leaky ReLU due to the exponential function.

7.  **Softmax Function**
    *   **Formula:** For a vector of inputs $Z = [Z_1, Z_2, ..., Z_k]$, the softmax function outputs a probability distribution $P = [P_1, P_2, ..., P_k]$ where $P_i = \frac{e^{Z_i}}{\sum_{j=1}^{k} e^{Z_j}}$
    *   **Output Range:** $(0, 1)$ for each element, and the sum of all elements is 1.
    *   **Use Cases:** Primarily used in the output layer for multi-class classification problems, where each output neuron represents the probability of belonging to a certain class.
    *   **Pros:** Produces a valid probability distribution, useful for multi-class classification.
    *   **Cons:** Only suitable for output layers for classification problems.

#### Choosing an Activation Function

*   **Hidden Layers:** ReLU is generally the default choice due to its efficiency and effectiveness. Leaky ReLU, PReLU, or ELU can be used to mitigate the dying ReLU problem, especially in deeper networks. Tanh can also be a good alternative, especially if zero-centered outputs are beneficial.
*   **Output Layer:**
    *   **Binary Classification:** Sigmoid (to output a probability between 0 and 1).
    *   **Multi-class Classification:** Softmax (to output a probability distribution over multiple classes).
    *   **Regression:** Linear activation (or no activation function), as the output should not be squashed into a range, but rather represent a continuous value.

The choice often depends on the specific problem, network architecture, and experimentation. It's common to start with ReLU for hidden layers and then explore other options if issues like dying ReLUs or slow convergence arise.

## 🧠 Why ANN Works

Artificial Neural Networks (ANNs) are incredibly powerful and have achieved state-of-the-art results across a multitude of complex tasks. Their effectiveness stems from a combination of several key properties:

### 1. Universal Approximation Theorem

Perhaps the most fundamental reason ANNs work is due to the **Universal Approximation Theorem**. In its simplest form, this theorem states that a feedforward network with at least one hidden layer and a non-linear activation function (like ReLU or sigmoid) can approximate any continuous function to an arbitrary degree of accuracy. This means that, given enough neurons and appropriate weights, an ANN can learn to represent extremely complex relationships between input and output data, no matter how intricate.

### 2. Hierarchical Feature Learning

ANNs, especially deep neural networks (DNNs), excel at **hierarchical feature learning**. Instead of relying on hand-engineered features, the network automatically learns relevant features from the raw input data in a layered fashion:

*   **Early Layers:** Tend to learn simple, low-level features (e.g., edges, corners, blobs in image processing; phonemes in speech recognition).
*   **Intermediate Layers:** Combine these simpler features to form more complex, abstract representations (e.g., parts of objects like eyes, noses, or ears).
*   **Later Layers:** Integrate these complex features to recognize high-level concepts (e.g., a full face, a complete word).

This automatic, hierarchical extraction of features is a major advantage over traditional machine learning models, which often require extensive feature engineering.

### 3. Non-linearity through Activation Functions

As discussed previously, **activation functions** are critical. Without them, stacking multiple layers would still result in a single linear transformation, meaning the network could only learn linear relationships. Real-world data is inherently non-linear, and activation functions introduce the necessary non-linearity, allowing the network to model highly complex, non-linear patterns.

### 4. Backpropagation and Gradient Descent

The efficiency of the **backpropagation algorithm** coupled with **gradient descent (and its variants)** is what makes training deep networks feasible. Backpropagation efficiently calculates the gradient of the loss function with respect to every weight and bias in the network. Gradient descent then uses these gradients to iteratively adjust the parameters in a direction that minimizes the error. This iterative optimization process allows the network to gradually learn from its mistakes and improve its predictions over time.

### 5. Distributed Representations

In ANNs, information is stored in a **distributed manner** across many neurons and connections, rather than in a single location. This distributed representation contributes to:

*   **Robustness:** The network can still function reasonably well even if some neurons are damaged or perturbed.
*   **Generalization:** The network can generalize effectively to unseen data because it learns broad patterns rather than memorizing specific examples.
*   **Efficiency:** A large number of concepts can be represented by combining the activity of a relatively small number of neurons.

### 6. Parallel Processing

The architecture of ANNs is inherently suitable for **parallel processing**. Computations within each layer (e.g., weighted sums for multiple neurons) can often be performed simultaneously. This is why GPUs (Graphics Processing Units) are so effective for training neural networks, as they are designed for massive parallel computations.

### 7. Big Data and Computational Power

The rise of **big data** and significant advancements in **computational power** (especially with GPUs and TPUs) have been crucial enablers for the success of ANNs. With more data, ANNs can learn richer and more robust features. With more computational power, larger and deeper networks can be trained, capable of tackling increasingly complex problems.

### In Summary

ANNs work because they combine several powerful concepts:
*   **Universal Approximation:** Can learn any complex function.
*   **Hierarchical Feature Learning:** Automatically extracts meaningful features from raw data.
*   **Non-linearity:** Enables modeling of complex, real-world patterns.
*   **Efficient Optimization:** Backpropagation and Gradient Descent allow effective learning.
*   **Distributed Representations:** Provides robustness and generalization.
*   **Parallelism:** Leverages modern hardware for efficient training.
*   **Availability of Data & Compute:** Fuels their ability to learn and scale.

Together, these factors allow ANNs to learn highly abstract and meaningful representations of data, enabling them to solve problems that were previously intractable for traditional computing methods.

## 🏗️ Simple ANN Example (Concept)

Let's walk through a very simple conceptual example of an Artificial Neural Network to understand how it processes information and learns. We'll use a straightforward problem: predicting whether a student will pass an exam based on two factors: **hours studied** and **previous exam score**.

### Problem Statement:

Given:
*   `Hours Studied` (Input 1)
*   `Previous Exam Score` (Input 2)

Predict:
*   `Pass/Fail` (Output)

### Network Architecture:

We'll design a very basic feedforward ANN with:
*   An **Input Layer** with 2 neurons (for 'Hours Studied' and 'Previous Exam Score').
*   A single **Hidden Layer** with 2 neurons.
*   An **Output Layer** with 1 neuron (for 'Pass' or 'Fail').

For activation functions, we'll use:
*   **ReLU** for the hidden layer neurons (for simplicity, but could be Tanh).
*   **Sigmoid** for the output layer neuron (to get a probability between 0 and 1, which we can threshold to 'Pass' or 'Fail').

```mermaid
graph TD
    A[Hours Studied] --> B{Hidden Neuron 1}
    A --> C{Hidden Neuron 2}
    D[Previous Exam Score] --> B
    D --> C
    B --> E[Output Neuron]
    C --> E
    E --> F[Pass/Fail]
```

### How It Works (Conceptual Walkthrough):

#### Phase 1: Forward Propagation (Making a Prediction)

Let's imagine a student studied for `5 hours` and had a `previous score of 70`. The network will process this information:

1.  **Input Layer:**
    *   Input to Neuron 1 = 5 (Hours Studied)
    *   Input to Neuron 2 = 70 (Previous Exam Score)

2.  **Hidden Layer:**
    *   Each input is multiplied by a **weight** and summed up with a **bias** for each hidden neuron. Let's assume some arbitrary initial weights and biases (these are learned during training).

    *   **For Hidden Neuron 1:**
        *   `Z_H1 = (5 * W_A_H1) + (70 * W_D_H1) + B_H1`
        *   `A_H1 = ReLU(Z_H1)`  (If `Z_H1` is negative, `A_H1` becomes 0; otherwise, it's `Z_H1`)

    *   **For Hidden Neuron 2:**
        *   `Z_H2 = (5 * W_A_H2) + (70 * W_D_H2) + B_H2`
        *   `A_H2 = ReLU(Z_H2)`

    *   *(Note: The 'W' values are weights, and 'B' values are biases. These are initially random and get adjusted during training.)*

3.  **Output Layer:**
    *   The activations from the hidden layer (`A_H1`, `A_H2`) now become inputs to the output neuron.

    *   **For Output Neuron:**
        *   `Z_Output = (A_H1 * W_H1_Out) + (A_H2 * W_H2_Out) + B_Out`
        *   `Prediction = Sigmoid(Z_Output)`

    *   The `Prediction` will be a value between 0 and 1. Let's say it comes out as `0.7`.

4.  **Final Decision:**
    *   We set a threshold, e.g., if `Prediction > 0.5`, then `Pass`, else `Fail`.
    *   In this case, `0.7 > 0.5`, so the network **predicts: Pass**.

#### Phase 2: Backpropagation (Learning from Mistakes)

Now, let's say the actual outcome for this student was `Fail` (meaning 0). The network made a mistake (predicted 0.7, but it should have been 0).

1.  **Calculate Loss:**
    *   A **Loss Function** (e.g., Binary Cross-Entropy for this classification problem) quantifies this error. A large error means the network's current weights and biases are far from optimal.

2.  **Backpropagation:**
    *   The error is propagated backward through the network, layer by layer, starting from the output layer.
    *   Using calculus (specifically, the **chain rule**), the algorithm calculates how much each individual weight and bias contributed to this error.
    *   This gives us the **gradient** for each weight and bias – essentially, the direction and magnitude by which each parameter should change to reduce the error.

3.  **Gradient Descent (Parameter Update):**
    *   An **Optimizer** (like Gradient Descent) then uses these gradients.
    *   It adjusts each weight and bias in the direction that *decreases* the loss, by a small step determined by the **learning rate**.
        *   `New Weight = Old Weight - (Learning Rate * Gradient)`
        *   `New Bias = Old Bias - (Learning Rate * Gradient)`

#### Iteration and Convergence:

This entire process (forward propagation to make a prediction, calculate loss, backpropagate error, and update parameters via gradient descent) is repeated hundreds, thousands, or even millions of times with many different student examples.

With each iteration, the network's weights and biases are slightly adjusted, and the network gradually gets better at making accurate predictions. Over time, the loss function decreases, and the network "learns" the complex relationship between study hours, previous scores, and passing the exam, effectively building a model that can generalize to new, unseen students.

In [1]:
import numpy as np

# --- Activation Functions ---
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sigmoid_derivative(a):
    return a * (1 - a)

def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)

print("Activation functions defined.")

Activation functions defined.


In [2]:
# --- Initialize Parameters ---
# Inputs: 2 (Hours Studied, Previous Exam Score)
# Hidden Layer: 2 neurons
# Output Layer: 1 neuron (Pass/Fail probability)

np.random.seed(42) # for reproducibility

# Weights and biases for Input Layer to Hidden Layer (2x2 matrix for W, 2x1 vector for b)
W1 = np.random.randn(2, 2) * 0.01
b1 = np.zeros((2, 1))

# Weights and biases for Hidden Layer to Output Layer (1x2 matrix for W, 1x1 vector for b)
W2 = np.random.randn(1, 2) * 0.01
b2 = np.zeros((1, 1))

print("Initial weights and biases:")
print("W1:\n", W1)
print("b1:\n", b1)
print("W2:\n", W2)
print("b2:\n", b2)

Initial weights and biases:
W1:
 [[ 0.00496714 -0.00138264]
 [ 0.00647689  0.0152303 ]]
b1:
 [[0.]
 [0.]]
W2:
 [[-0.00234153 -0.00234137]]
b2:
 [[0.]]


In [3]:
# --- Forward Propagation Example ---

# Sample Input: Student studied 5 hours (scaled), previous score 70 (scaled)
# We'll use scaled inputs for better numerical stability in ANNs.
# Let's say 5 hours -> 0.5, 70 score -> 0.7 (hypothetical scaling for demonstration)
# A real example would use proper standardization or normalization.
X = np.array([[0.5], [0.7]]) # (2, 1) matrix for 2 inputs, 1 example

print(f"Input (X):\n{X}\n")

# --- Hidden Layer Calculation ---
# Z_H = W1 * X + b1
Z1 = np.dot(W1, X) + b1
A1 = relu(Z1) # Apply ReLU activation

print("Hidden Layer (Z1):\n", Z1)
print("Hidden Layer Activation (A1):\n", A1)

# --- Output Layer Calculation ---
# Z_Out = W2 * A1 + b2
Z2 = np.dot(W2, A1) + b2
A2 = sigmoid(Z2) # Apply Sigmoid activation for probability output

print("Output Layer (Z2):\n", Z2)
print("Final Prediction (A2):\n", A2)

# Interpret prediction
threshold = 0.5
predicted_class = "Pass" if A2 > threshold else "Fail"
print(f"Predicted class: {predicted_class} (Probability: {A2[0][0]:.4f})")

Input (X):
[[0.5]
 [0.7]]

Hidden Layer (Z1):
 [[0.00151572]
 [0.01389965]]
Hidden Layer Activation (A1):
 [[0.00151572]
 [0.01389965]]
Output Layer (Z2):
 [[-3.60933326e-05]]
Final Prediction (A2):
 [[0.49999098]]
Predicted class: Fail (Probability: 0.5000)


In [4]:
# --- Loss Function Calculation (Binary Cross-Entropy) ---

# Assume the true outcome for this student was 'Fail' (y=0)
y_true = np.array([[0]])

# Binary Cross-Entropy Loss
def compute_loss(y_pred, y_true):
    epsilon = 1e-10 # to prevent log(0)
    loss = - (y_true * np.log(y_pred + epsilon) + (1 - y_true) * np.log(1 - y_pred + epsilon))
    return np.squeeze(loss) # remove redundant dimensions

loss = compute_loss(A2, y_true)
print(f"True label (y_true): {y_true[0][0]}")
print(f"Calculated Loss: {loss:.4f}")

True label (y_true): 0
Calculated Loss: 0.6931


In [5]:
# --- Backpropagation Example ---

# Learning Rate
learning_rate = 0.1

# --- Step 1: Calculate gradient for the Output Layer ---
# dL/dA2 (derivative of loss w.r.t. A2 for Binary Cross-Entropy)
dA2 = - (np.divide(y_true, A2) - np.divide(1 - y_true, 1 - A2))

# dA2/dZ2 (derivative of Sigmoid w.r.t. Z2)
dZ2 = dA2 * sigmoid_derivative(A2)

# dZ2/dW2 = A1.T
dW2 = np.dot(dZ2, A1.T)

# dZ2/db2 = 1
db2 = dZ2

# --- Step 2: Calculate gradient for the Hidden Layer ---
# dL/dA1 = dL/dZ2 * dZ2/dA1 = (W2.T * dZ2)
dA1 = np.dot(W2.T, dZ2)

# dA1/dZ1 (derivative of ReLU w.r.t. Z1)
dZ1 = dA1 * relu_derivative(Z1)

# dZ1/dW1 = X.T
dW1 = np.dot(dZ1, X.T)

# dZ1/db1 = 1
db1 = dZ1

print("Gradients computed:")
print("dW1:\n", dW1)
print("db1:\n", db1)
print("dW2:\n", dW2)
print("db2:\n", db2)

Gradients computed:
dW1:
 [[-0.00058537 -0.00081952]
 [-0.00058533 -0.00081946]]
db1:
 [[-0.00117075]
 [-0.00117066]]
dW2:
 [[0.00075785 0.0069497 ]]
db2:
 [[0.49999098]]


In [6]:
# --- Parameter Update (Gradient Descent) ---

print("Original W1:\n", W1)
print("Original b1:\n", b1)
print("Original W2:\n", W2)
print("Original b2:\n", b2)

# Update weights and biases
W1 = W1 - learning_rate * dW1
b1 = b1 - learning_rate * db1
W2 = W2 - learning_rate * dW2
b2 = b2 - learning_rate * db2

print("\nUpdated Weights and Biases (after one step of gradient descent):")
print("Updated W1:\n", W1)
print("Updated b1:\n", b1)
print("Updated W2:\n", W2)
print("Updated b2:\n", b2)

Original W1:
 [[ 0.00496714 -0.00138264]
 [ 0.00647689  0.0152303 ]]
Original b1:
 [[0.]
 [0.]]
Original W2:
 [[-0.00234153 -0.00234137]]
Original b2:
 [[0.]]

Updated Weights and Biases (after one step of gradient descent):
Updated W1:
 [[ 0.00502568 -0.00130069]
 [ 0.00653542  0.01531225]]
Updated b1:
 [[0.00011707]
 [0.00011707]]
Updated W2:
 [[-0.00241732 -0.00303634]]
Updated b2:
 [[-0.0499991]]


In [7]:
# --- Putting it all together: A Simple Training Loop ---

# Re-initialize parameters for a fresh training run
np.random.seed(42)
W1 = np.random.randn(2, 2) * 0.01
b1 = np.zeros((2, 1))
W2 = np.random.randn(1, 2) * 0.01
b2 = np.zeros((1, 1))

learning_rate = 0.1
epochs = 1000

# Sample Data (scaled)
# Student 1: 5 hrs, 70 score -> Fail (0)
# Student 2: 9 hrs, 85 score -> Pass (1)
# Student 3: 3 hrs, 60 score -> Fail (0)
# Student 4: 7 hrs, 90 score -> Pass (1)
X_train = np.array([[0.5, 0.9, 0.3, 0.7],    # Hours Studied
                    [0.7, 0.85, 0.6, 0.9]]) # Previous Score
y_train = np.array([[0, 1, 0, 1]])          # True Labels

# Training loop
for epoch in range(epochs):
    # Forward Propagation
    Z1 = np.dot(W1, X_train) + b1
    A1 = relu(Z1)
    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2)

    # Compute Loss (average over all examples)
    loss = np.mean(compute_loss(A2, y_train))

    # Backpropagation
    dA2 = - (np.divide(y_train, A2) - np.divide(1 - y_train, 1 - A2))
    dZ2 = dA2 * sigmoid_derivative(A2)
    dW2 = np.dot(dZ2, A1.T)
    db2 = np.sum(dZ2, axis=1, keepdims=True)

    dA1 = np.dot(W2.T, dZ2)
    dZ1 = dA1 * relu_derivative(Z1)
    dW1 = np.dot(dZ1, X_train.T)
    db1 = np.sum(dZ1, axis=1, keepdims=True)

    # Update Parameters
    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

print("\nTraining complete.")
print("Final Loss: {loss:.4f}".format(loss=loss))

# Test with a new example (e.g., student studied 6 hours, score 75 -> should pass)
X_new = np.array([[0.6], [0.75]]) # Scaled inputs

Z1_test = np.dot(W1, X_new) + b1
A1_test = relu(Z1_test)
Z2_test = np.dot(W2, A1_test) + b2
A2_test = sigmoid(Z2_test)

predicted_class_test = "Pass" if A2_test > threshold else "Fail"
print(f"\nPrediction for new student (Hours: 0.6, Score: 0.75): {predicted_class_test} (Probability: {A2_test[0][0]:.4f})")

Epoch 0, Loss: 0.6932
Epoch 100, Loss: 0.6718
Epoch 200, Loss: 0.2023
Epoch 300, Loss: 0.0681
Epoch 400, Loss: 0.0346
Epoch 500, Loss: 0.0219
Epoch 600, Loss: 0.0156
Epoch 700, Loss: 0.0120
Epoch 800, Loss: 0.0097
Epoch 900, Loss: 0.0081

Training complete.
Final Loss: 0.0069

Prediction for new student (Hours: 0.6, Score: 0.75): Fail (Probability: 0.3372)


#Example 2

In [8]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [9]:
# Input features (10 features per sample)
X = np.random.rand(1000, 10)

# Output labels (0 or 1)
y = np.random.randint(0, 2, 1000)

In [10]:
model = Sequential()

# Input + Hidden Layer
model.add(Dense(16, activation='relu', input_dim=10))

# Hidden Layer
model.add(Dense(8, activation='relu'))

# Output Layer
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [14]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [15]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 16)             │           176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.fit(X, y, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.4825 - loss: 0.7047 - val_accuracy: 0.4850 - val_loss: 0.6981
Epoch 2/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5013 - loss: 0.6976 - val_accuracy: 0.5200 - val_loss: 0.6963
Epoch 3/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5000 - loss: 0.6962 - val_accuracy: 0.5350 - val_loss: 0.6968
Epoch 4/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5075 - loss: 0.6949 - val_accuracy: 0.5450 - val_loss: 0.6949
Epoch 5/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5050 - loss: 0.6943 - val_accuracy: 0.5400 - val_loss: 0.6939
Epoch 6/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4988 - loss: 0.6935 - val_accuracy: 0.5200 - val_loss: 0.6938
Epoch 7/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4913 - loss: 0.6929 - val_accuracy: 0.5300 - val_loss: 0.6932
Epoch 8/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5025 - loss: 0.6921 - val_accuracy: 0.5250 - val_loss

In [17]:
# New email data (example)
new_data = np.random.rand(1, 10)

prediction = model.predict(new_data)

print("Spam Probability:", prediction)

# Convert to class
if prediction > 0.5:
    print("Spam")
else:
    print("Not Spam")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step
Spam Probability: [[0.4786538]]
Not Spam
