<a href="https://colab.research.google.com/github/faisu6339-glitch/Deep-Learning/blob/main/Backpropagation_in_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Backpropagation in Convolutional Neural Networks (CNNs)

Backpropagation is the fundamental algorithm for training artificial neural networks, including CNNs. It's an efficient way to calculate the gradient of the loss function with respect to the network's weights, allowing the network to adjust its parameters to minimize error.

### How Backpropagation Works in CNNs

In a standard feedforward neural network, backpropagation involves propagating the error backward through the layers, adjusting weights based on their contribution to the error. For CNNs, this process is similar but has specific considerations due to the unique operations (convolution, pooling) involved.

1.  **Forward Pass**: Input data passes through the convolutional layers, activation functions, pooling layers, and finally fully connected layers to produce an output prediction.

2.  **Loss Calculation**: The predicted output is compared to the actual target output, and a loss function (e.g., Cross-Entropy for classification, Mean Squared Error for regression) calculates the error.

3.  **Backward Pass (Gradient Calculation)**:
    *   **Output Layer**: The gradients of the loss with respect to the output layer's activations and weights are calculated first.
    *   **Fully Connected Layers**: Standard backpropagation applies to these layers, similar to an MLP.
    *   **Pooling Layers (e.g., Max Pooling)**: The gradient is passed *only* to the neuron that had the maximum activation during the forward pass. All other neurons in the receptive field receive a gradient of zero. This means the error signal is sparse.
    *   **Convolutional Layers**: This is where it gets interesting.
        *   **Weight Gradients**: To update the filter weights, the error signal from the subsequent layer is convolved with the input to the current convolutional layer. This is essentially a *"backward convolution"*.
        *   **Input Gradients (for previous layer)**: To pass the error backward to the previous layer, the filters themselves are *rotated 180 degrees* and then convolved with the error signal from the current layer. This effectively performs an upsampling and convolution operation to spread the error.

4.  **Parameter Update**: An optimization algorithm (e.g., Stochastic Gradient Descent, Adam, RMSprop) uses these calculated gradients to adjust the weights and biases of all layers, aiming to reduce the loss in subsequent iterations.

### Key Components and Their Role in Backpropagation

#### 1. Activation Functions
Activation functions (like ReLU, Sigmoid, Tanh) introduce non-linearity, allowing the network to learn complex patterns. During backpropagation, their derivatives are crucial for calculating how much each neuron's activation contributed to the overall error. For example, the derivative of ReLU is 1 for positive inputs and 0 for negative inputs, meaning only active neurons propagate gradients.

#### 2. Loss Functions
The choice of loss function directly impacts the error signal generated. Common loss functions include:
*   **Cross-Entropy Loss**: Widely used for classification tasks. It penalizes incorrect predictions more heavily.
*   **Mean Squared Error (MSE)**: Typically used for regression tasks. It measures the average squared difference between predicted and actual values.
The derivative of the loss function is the starting point for backpropagation, defining the initial error signal that propagates backward through the network.

### In Summary

Backpropagation in CNNs is a sophisticated application of the chain rule of calculus. It efficiently computes the gradients needed to update the network's convolutional filters, pooling operations, and fully connected layer weights, enabling CNNs to learn powerful feature representations from data for tasks like image classification, object detection, and more.

# Backpropagation in Convolutional Neural Networks (CNNs)

Backpropagation is the learning mechanism of a CNN.

It helps the network:
- Calculate prediction error
- Find responsible filters/kernels
- Update weights
- Improve future predictions

Without backpropagation, CNNs cannot learn image features such as:
- edges
- textures
- shapes
- objects

#CNN Learning Flow Diagram

# CNN Learning Process

```text
INPUT IMAGE
     ↓
CONVOLUTION
     ↓
RELU
     ↓
POOLING
     ↓
FLATTEN
     ↓
FULLY CONNECTED
     ↓
OUTPUT
     ↓
LOSS FUNCTION
     ↓
BACKPROPAGATION
     ↓
WEIGHT UPDATE


---

# 3. Forward and Backward Pass

```markdown
# Forward Pass vs Backward Pass

## Forward Pass
The input image passes through:
1. Convolution Layer
2. Activation Function (ReLU)
3. Pooling Layer
4. Fully Connected Layer
5. Output Layer

Prediction is generated.

---

## Backward Pass
The network:
1. Calculates loss
2. Sends error backward
3. Computes gradients
4. Updates filters and weights

# Gradient Descent Formula

\[
W_{new} = W_{old} - \eta \frac{\partial L}{\partial W}
\]

Where:
- \(W\) = weight
- \(\eta\) = learning rate
- \(L\) = loss function
- \(\frac{\partial L}{\partial W}\) = gradient

# Cross Entropy Loss

\[
L = -\sum y \log(\hat{y})
\]

Where:
- \(y\) = actual label
- \(\hat{y}\) = predicted output

# Chain Rule in Backpropagation

\[
\frac{\partial L}{\partial W}
=
\frac{\partial L}{\partial O}
\times
\frac{\partial O}{\partial W}
\]

Where:
- \(L\) = Loss
- \(O\) = Output
- \(W\) = Weight

# ReLU Activation Function

\[
f(x) = \max(0, x)
\]

## ReLU Gradient

- If \(x > 0\), gradient = 1
- If \(x \leq 0\), gradient = 0

# Backpropagation Through Max Pooling

## Forward Pass

```text
2  8
5  1


---

# 9. Convolution Backpropagation (Markdown Cell)

```markdown
# Backpropagation Through Convolution Layer

During backpropagation CNN computes:

1. Filter Gradients
2. Input Gradients
3. Bias Gradients

---

## Kernel Gradient Formula

\[
\frac{\partial L}{\partial K}
=
X * \frac{\partial L}{\partial Y}
\]

Where:
- \(K\) = kernel
- \(X\) = input image
- \(Y\) = output feature map

---

## Input Gradient Formula

\[
\frac{\partial L}{\partial X}
=
\frac{\partial L}{\partial Y} * K_{rotated}
\]

Kernel is rotated by 180° during backward convolution.

# Complete CNN Backpropagation Flow

```text
FORWARD PASS
-----------------------------------------
Input
  ↓
Convolution
  ↓
ReLU
  ↓
Pooling
  ↓
Flatten
  ↓
Fully Connected
  ↓
Prediction
  ↓
Loss
-----------------------------------------

BACKWARD PASS
-----------------------------------------
Loss Gradient
  ↓
FC Gradients
  ↓
Pooling Gradients
  ↓
ReLU Gradients
  ↓
Convolution Gradients
  ↓
Filter Updates
-----------------------------------------


---

# 11. Vanishing Gradient Problem (Markdown Cell)

```markdown
# Vanishing Gradient Problem

Sometimes gradients become extremely small.

Example:

```text
Layer 10 → 0.9
Layer 20 → 0.1
Layer 30 → 0.00001


---

# 12. Exploding Gradient Problem (Markdown Cell)

```markdown
# Exploding Gradient Problem

Sometimes gradients become extremely large.

Effects:
- Unstable training
- Loss becomes NaN

## Solutions
- Gradient Clipping
- Smaller Learning Rate
- Batch Normalization

# Forward Pass
output = CNN(input)

# Calculate Loss
loss = criterion(output, target)

# Backward Pass
loss.backward()

# Update Weights
optimizer.step()

#Understanding Backpropagation in CNN with Code

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [9]:
# Input Image
x = torch.tensor([[[

    [1., 2., 3., 0., 1., 2.],
    [0., 1., 2., 3., 1., 0.],
    [1., 0., 1., 2., 3., 1.],
    [2., 1., 0., 1., 2., 3.],
    [3., 2., 1., 0., 1., 2.],
    [0., 1., 2., 1., 0., 1.]

]]])
print(x.shape)

torch.Size([1, 1, 6, 6])


| Value | Meaning    |
| ----- | ---------- |
| 1     | batch size |
| 1     | channel    |
| 6     | height     |
| 6     | width      |


#3. Create CNN Model

Now create:

Convolution
ReLU
Pooling
Fully Connected Layer

In [3]:
class SimpleCNN(nn.Module):

    def __init__(self):

        super(SimpleCNN, self).__init__()

        # Convolution Layer
        self.conv = nn.Conv2d(
            in_channels=1,
            out_channels=1,
            kernel_size=3
        )

        # ReLU
        self.relu = nn.ReLU()

        # Max Pooling
        self.pool = nn.MaxPool2d(kernel_size=2)

        # Fully Connected Layer
        self.fc = nn.Linear(4, 1)

    def forward(self, x):

        print("\nINPUT IMAGE")
        print(x)

        # Convolution
        x = self.conv(x)

        print("\nAFTER CONVOLUTION")
        print(x)

        # ReLU
        x = self.relu(x)

        print("\nAFTER RELU")
        print(x)

        # Pooling
        x = self.pool(x)

        print("\nAFTER POOLING")
        print(x)

        # Flatten
        x = x.view(x.size(0), -1)

        print("\nAFTER FLATTEN")
        print(x)

        # Fully Connected
        x = self.fc(x)

        print("\nFINAL OUTPUT")
        print(x)

        return x

#4. Create Model

In [4]:
model = SimpleCNN()

#5. Define Loss Function

We use:

Binary Cross Entropy

In [5]:
criterion = nn.BCEWithLogitsLoss()

#6. Define Optimizer

Optimizer updates weights.

In [6]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

#7. Create Target Label

In [7]:
target = torch.tensor([[1.]])

#8. Forward Pass

In [10]:
output = model(x)


INPUT IMAGE
tensor([[[[1., 2., 3., 0., 1., 2.],
          [0., 1., 2., 3., 1., 0.],
          [1., 0., 1., 2., 3., 1.],
          [2., 1., 0., 1., 2., 3.],
          [3., 2., 1., 0., 1., 2.],
          [0., 1., 2., 1., 0., 1.]]]])

AFTER CONVOLUTION
tensor([[[[ 0.4958,  0.1395, -0.6701,  1.3961],
          [ 0.9164,  0.4958,  0.3027, -0.5517],
          [ 0.3642,  0.9164,  0.4958,  0.3027],
          [-0.4093,  0.2819,  0.9164,  0.4958]]]],
       grad_fn=<ConvolutionBackward0>)

AFTER RELU
tensor([[[[0.4958, 0.1395, 0.0000, 1.3961],
          [0.9164, 0.4958, 0.3027, 0.0000],
          [0.3642, 0.9164, 0.4958, 0.3027],
          [0.0000, 0.2819, 0.9164, 0.4958]]]], grad_fn=<ReluBackward0>)

AFTER POOLING
tensor([[[[0.9164, 1.3961],
          [0.9164, 0.9164]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)

AFTER FLATTEN
tensor([[0.9164, 1.3961, 0.9164, 0.9164]], grad_fn=<ViewBackward0>)

FINAL OUTPUT
tensor([[-0.6453]], grad_fn=<AddmmBackward0>)


#What Happens Internally?

Input Image
      ↓
Convolution
      ↓
ReLU
      ↓
Pooling
      ↓
Flatten
      ↓
Fully Connected
      ↓
Prediction

#9. Compute Loss

In [11]:
loss = criterion(output, target)

print("\nLOSS")
print(loss)


LOSS
tensor(1.0670, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


#10. Backpropagation Begins

In [12]:
optimizer.zero_grad()

loss.backward()

#Convolution Filter Gradients

In [13]:
print("\nCONVOLUTION FILTER GRADIENTS")

print(model.conv.weight.grad)


CONVOLUTION FILTER GRADIENTS
tensor([[[[0.0000, 0.3601, 0.7201],
          [0.7310, 0.1855, 0.1746],
          [0.7201, 0.7310, 0.1855]]]])


#Fully Connected Layer Gradients

In [14]:
print("\nFC LAYER GRADIENTS")

print(model.fc.weight.grad)


FC LAYER GRADIENTS
tensor([[-0.6011, -0.9158, -0.6011, -0.6011]])


#12. Update Weights

In [15]:
optimizer.step()

#13. Print Updated Weights

In [16]:
print("\nUPDATED CONVOLUTION FILTER")

print(model.conv.weight)


UPDATED CONVOLUTION FILTER
Parameter containing:
tensor([[[[-0.2700,  0.2779,  0.1559],
          [ 0.0205,  0.0258,  0.0189],
          [ 0.0339,  0.3233, -0.2458]]]], requires_grad=True)
