<a href="https://colab.research.google.com/github/faisu6339-glitch/Deep-Learning/blob/main/LSTM(Next_Word_Prediction).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [11]:
text = """
I love machine learning
I love deep learning
I love artificial intelligence
Machine learning is amazing
Deep learning is powerful
Artificial intelligence is the future
Machine learning is fun
Machine learning is useful
Machine learning is interesting
Machine learning helps solve problems
Machine learning uses data
Machine learning builds intelligent systems
Machine learning improves predictions
Machine learning changes the world
Machine learning requires practice
Machine learning makes automation possible

Deep learning is amazing
Deep learning uses neural networks
Deep learning learns from data
Deep learning improves accuracy
Deep learning powers AI applications
Deep learning is used in healthcare
Deep learning is used in robotics
Deep learning is used in self driving cars
Deep learning can recognize images
Deep learning can understand speech
Deep learning requires large datasets
Deep learning requires GPUs

Artificial intelligence is amazing
Artificial intelligence is powerful
Artificial intelligence is everywhere
Artificial intelligence improves technology
Artificial intelligence helps people
Artificial intelligence powers chatbots
Artificial intelligence powers robots
Artificial intelligence is transforming industries
Artificial intelligence is changing healthcare
Artificial intelligence is changing education
Artificial intelligence is changing finance
Artificial intelligence is changing transportation

Python is popular for machine learning
Python is easy to learn
Python supports deep learning
Python has powerful libraries
Python is widely used in AI
Python is beginner friendly
Python makes programming easy

TensorFlow is a deep learning framework
TensorFlow is developed for AI
TensorFlow supports neural networks
TensorFlow makes model training easy
TensorFlow is popular among developers

Keras is simple and powerful
Keras works with TensorFlow
Keras helps build neural networks
Keras makes deep learning easier
Keras supports LSTM models

Neural networks learn patterns
Neural networks process data
Neural networks improve predictions
Neural networks have many layers
Neural networks are inspired by the human brain

Data is important for machine learning
Good data improves model accuracy
Clean data produces better results
Large datasets improve performance
Training data teaches the model
Testing data evaluates the model
Validation data prevents overfitting

AI is changing the future
AI helps doctors diagnose diseases
AI improves business decisions
AI makes life easier
AI is used in education
AI is used in banking
AI is used in agriculture
AI is used in security
AI is used in transportation
AI is used in entertainment

Students love learning AI
Developers build AI applications
Researchers improve AI models
Companies invest in artificial intelligence
Scientists study machine learning
Engineers create intelligent systems
Technology is evolving rapidly
The future belongs to artificial intelligence
Learning never stops in AI
Practice makes machine learning easier
"""

#Tokenization

In [12]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])

total_words=len(tokenizer.word_index)+1
print("Vocabulary Size=",total_words)


Vocabulary Size= 144


#Word Index

In [13]:
print(tokenizer.word_index)

{'learning': 1, 'is': 2, 'deep': 3, 'ai': 4, 'machine': 5, 'artificial': 6, 'intelligence': 7, 'in': 8, 'used': 9, 'data': 10, 'neural': 11, 'networks': 12, 'the': 13, 'python': 14, 'makes': 15, 'tensorflow': 16, 'improves': 17, 'changing': 18, 'keras': 19, 'love': 20, 'powerful': 21, 'helps': 22, 'model': 23, 'i': 24, 'amazing': 25, 'future': 26, 'requires': 27, 'powers': 28, 'for': 29, 'easy': 30, 'supports': 31, 'easier': 32, 'improve': 33, 'uses': 34, 'intelligent': 35, 'systems': 36, 'predictions': 37, 'practice': 38, 'accuracy': 39, 'applications': 40, 'healthcare': 41, 'can': 42, 'large': 43, 'datasets': 44, 'technology': 45, 'education': 46, 'transportation': 47, 'popular': 48, 'to': 49, 'learn': 50, 'training': 51, 'developers': 52, 'build': 53, 'models': 54, 'fun': 55, 'useful': 56, 'interesting': 57, 'solve': 58, 'problems': 59, 'builds': 60, 'changes': 61, 'world': 62, 'automation': 63, 'possible': 64, 'learns': 65, 'from': 66, 'robotics': 67, 'self': 68, 'driving': 69, 'ca

#Create Input Sequences

#Example
I love machine learning

↓

I love

I love machine

I love machine learning

In [16]:
input_sequences = []

for line in text.split("\n"):

    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram = token_list[:i+1]
        input_sequences.append(n_gram)

In [17]:
for seq in input_sequences:
    print(seq)

[24, 20]
[24, 20, 5]
[24, 20, 5, 1]
[24, 20]
[24, 20, 3]
[24, 20, 3, 1]
[24, 20]
[24, 20, 6]
[24, 20, 6, 7]
[5, 1]
[5, 1, 2]
[5, 1, 2, 25]
[3, 1]
[3, 1, 2]
[3, 1, 2, 21]
[6, 7]
[6, 7, 2]
[6, 7, 2, 13]
[6, 7, 2, 13, 26]
[5, 1]
[5, 1, 2]
[5, 1, 2, 55]
[5, 1]
[5, 1, 2]
[5, 1, 2, 56]
[5, 1]
[5, 1, 2]
[5, 1, 2, 57]
[5, 1]
[5, 1, 22]
[5, 1, 22, 58]
[5, 1, 22, 58, 59]
[5, 1]
[5, 1, 34]
[5, 1, 34, 10]
[5, 1]
[5, 1, 60]
[5, 1, 60, 35]
[5, 1, 60, 35, 36]
[5, 1]
[5, 1, 17]
[5, 1, 17, 37]
[5, 1]
[5, 1, 61]
[5, 1, 61, 13]
[5, 1, 61, 13, 62]
[5, 1]
[5, 1, 27]
[5, 1, 27, 38]
[5, 1]
[5, 1, 15]
[5, 1, 15, 63]
[5, 1, 15, 63, 64]
[3, 1]
[3, 1, 2]
[3, 1, 2, 25]
[3, 1]
[3, 1, 34]
[3, 1, 34, 11]
[3, 1, 34, 11, 12]
[3, 1]
[3, 1, 65]
[3, 1, 65, 66]
[3, 1, 65, 66, 10]
[3, 1]
[3, 1, 17]
[3, 1, 17, 39]
[3, 1]
[3, 1, 28]
[3, 1, 28, 4]
[3, 1, 28, 4, 40]
[3, 1]
[3, 1, 2]
[3, 1, 2, 9]
[3, 1, 2, 9, 8]
[3, 1, 2, 9, 8, 41]
[3, 1]
[3, 1, 2]
[3, 1, 2, 9]
[3, 1, 2, 9, 8]
[3, 1, 2, 9, 8, 67]
[3, 1]
[3, 1, 2]
[3, 1, 2, 9]
[

#Padding

In [18]:
max_sequence_len = max(len(seq) for seq in input_sequences)

print(max_sequence_len)

8


In [19]:
input_sequences = pad_sequences(
    input_sequences,
    maxlen=max_sequence_len,
    padding='pre'
)

In [20]:
print(input_sequences)

[[ 0  0  0 ...  0 24 20]
 [ 0  0  0 ... 24 20  5]
 [ 0  0  0 ... 20  5  1]
 ...
 [ 0  0  0 ... 38 15  5]
 [ 0  0  0 ... 15  5  1]
 [ 0  0  0 ...  5  1 32]]


#Split into X and y

In [21]:
X = input_sequences[:, :-1]

y = input_sequences[:, -1]

#One-Hot Encode Output

In [22]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)

In [23]:
print(X.shape)
print(y.shape)

(328, 7)
(328, 144)


#Build LSTM Model

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense

model = Sequential([
    Input(shape=(max_sequence_len-1,)),
    Embedding(input_dim=total_words, output_dim=64),
    LSTM(100),
    Dense(total_words, activation='softmax')
])

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 7, 64)          │         9,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100)            │        66,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 144)            │        14,544 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 89,760 (350.62 KB)

 Trainable params: 89,760 (350.62 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [30]:
history = model.fit(
    X,
    y,
    epochs=500,
    verbose=1
)

Epoch 1/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.1098 - loss: 4.9470
Epoch 2/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1067 - loss: 4.7047
Epoch 3/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0915 - loss: 4.3907
Epoch 4/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1250 - loss: 4.2453
Epoch 5/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1037 - loss: 4.1932
Epoch 6/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1433 - loss: 4.1430
Epoch 7/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1555 - loss: 4.1015
Epoch 8/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1250 - loss: 4.0544
Epoch 9/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1860 - loss: 3.9947
Epoch 10/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2073 - loss: 3.9294
Epoch 11/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2439 - loss: 3.8600
Epoch 12/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy

In [31]:
seed_text = "I love"

next_words = 3

for _ in range(next_words):

    token_list = tokenizer.texts_to_sequences([seed_text])[0]

    token_list = pad_sequences(
        [token_list],
        maxlen=max_sequence_len-1,
        padding='pre'
    )

    predicted = np.argmax(model.predict(token_list, verbose=0), axis=-1)[0]

    output_word = ""

    for word, index in tokenizer.word_index.items():

        if index == predicted:
            output_word = word
            break

    seed_text += " " + output_word

print(seed_text)

I love machine learning easier
