<a href="https://colab.research.google.com/github/faisu6339-glitch/Deep-Learning/blob/main/LSTM(Sequence_Window_Creation).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Convert

10 20 30 40 50 60

into

Input      Output

10 20 30 → 40

20 30 40 → 50

30 40 50 → 60

This teaches how LSTM datasets are prepared.

In [1]:
import numpy as np

#Step 2: Create Dataset

In [2]:
data=np.array([10,20,30,40,50,60])
print(data)

[10 20 30 40 50 60]


#Step 3: Decide Window Size

In [3]:
window_size = 3

What does this mean?

The model will look at 3 previous values to predict the next value.

Visual

10 20 30 → ?


Answer

40

#Step 4: Create Empty Lists
X = []
y = []

These lists will store:

Input sequences
Output values

Initially

X = []

y = []

In [5]:
X = []
y = []

#Step 5: Create Sequences

In [6]:
for i in range(len(data) - window_size):

    X.append(data[i:i+window_size])

    y.append(data[i+window_size])

#Iteration 1
i = 0

Input

data[0:3]

Output

[10 20 30]

Target

data[3]

Output

40

Now

X =

[
 [10 20 30]
]

y =

[
40
]

#Iteration 2
i = 1

Input

data[1:4]

Output

20 30 40

Target

data[4]

Output

50

Now

X

[
 [10 20 30]

 [20 30 40]
]

y

[
40

50
]

#Iteration 3
i = 2

Input

data[2:5]

Output

30 40 50

Target

data[5]

Output

60

X

[
 [10 20 30]

 [20 30 40]

 [30 40 50]
]

y

[
40

50

60
]

#Step 6: Convert into NumPy Arrays

In [7]:
X = np.array(X)
y = np.array(y)

In [8]:
print("Input:")
print(X)

print()

print("Output:")
print(y)

Input:
[[10 20 30]
 [20 30 40]
 [30 40 50]]

Output:
[40 50 60]


In [9]:
print(X.shape)

(3, 3)


In [10]:
X = X.reshape((X.shape[0], X.shape[1], 1))

In [11]:
print(X.shape)

(3, 3, 1)


Understanding (3,3,1)
Samples = 3

There are 3 training examples.

Sample 1

10 20 30

↓

40
Sample 2

20 30 40

↓

50
Sample 3

30 40 50

↓

60

Timesteps = 3

Each sample contains 3 previous values.

Example

10

↓

20

↓

30

The LSTM reads these values one by one, maintaining an internal memory as it processes the sequence.

Features = 1

Each timestep has only one feature (the number itself).

10

20

30