<a href="https://colab.research.google.com/github/faisu6339-glitch/Deep-Learning/blob/main/LSTM(Sequence_Window_Creation).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Convert

10 20 30 40 50 60

into

Input      Output

10 20 30 → 40

20 30 40 → 50

30 40 50 → 60

This teaches how LSTM datasets are prepared.

In [1]:
import numpy as np

#Step 2: Create Dataset

In [2]:
data=np.array([10,20,30,40,50,60])
print(data)

[10 20 30 40 50 60]


#Step 3: Decide Window Size

In [3]:
window_size = 3

What does this mean?

The model will look at 3 previous values to predict the next value.

Visual

10 20 30 → ?


Answer

40

#Step 4: Create Empty Lists
X = []
y = []

These lists will store:

Input sequences
Output values

Initially

X = []

y = []

In [5]:
X = []
y = []

#Step 5: Create Sequences

In [6]:
for i in range(len(data) - window_size):

    X.append(data[i:i+window_size])

    y.append(data[i+window_size])

### Step 1: Understanding `range(len(data) - window_size)`

First, let's calculate `len(data)`:

```
len(data)
```
Output:
```
6
```
because there are 6 numbers in our `data` array.

Now, `len(data) - window_size` becomes:

```
6 - 3 = 3
```
So, the loop effectively becomes:

```python
for i in range(3):
```
This means the variable `i` will take on the values `0`, `1`, and `2`. Only 3 iterations are needed.

---

### Iteration 1: `i = 0`

**First line: `X.append(data[i:i+window_size])`**

Substitute the values:

```python
X.append(data[0:3])
```
Remember Python slicing: `start : stop` includes the start index but excludes the stop index.

Our data and its indices are:

| Index | 0  | 1  | 2  | 3  | 4  | 5  |
|-------|----|----|----|----|----|----|
| Value | 10 | 20 | 30 | 40 | 50 | 60 |

So, `data[0:3]` takes the values at index 0, 1, and 2:

```
[10, 20, 30]
```
Now, `X.append([10,20,30])` results in:

```
X = [
    [10, 20, 30]
]
```

**Second line: `y.append(data[i+window_size])`**

Substitute values:

```python
y.append(data[0+3])  # which is data[3]
```
Index 3 contains the value `40`.

So, `y.append(40)` results in:

```
y = [
    40
]
```

**After Iteration 1:**

Input: `[10, 20, 30]`
Output: `40`

---

### Iteration 2: `i = 1`

**First line: `X.append(data[i:i+window_size])`**

Substitute values:

```python
X.append(data[1:4])
```
Using our indices table, `data[1:4]` takes the values at index 1, 2, and 3:

```
[20, 30, 40]
```
Now, `X` becomes:

```
X = [
    [10, 20, 30],
    [20, 30, 40]
]
```

**Second line: `y.append(data[i+window_size])`**

Substitute values:

```python
y.append(data[1+3])  # which is data[4]
```
Index 4 contains the value `50`.

Now, `y` becomes:

```
y = [
    40,
    50
]
```

**After Iteration 2:**

Input: `[20, 30, 40]`
Output: `50`

---

### Iteration 3: `i = 2`

**First line: `X.append(data[i:i+window_size])`**

Substitute values:

```python
X.append(data[2:5])
```
Using our indices table, `data[2:5]` takes the values at index 2, 3, and 4:

```
[30, 40, 50]
```
Now, `X` becomes:

```
X = [
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
]
```

**Second line: `y.append(data[i+window_size])`**

Substitute values:

```python
y.append(data[2+3])  # which is data[5]
```
Index 5 contains the value `60`.

Now, `y` becomes:

```
y = [
    40,
    50,
    60
]
```

**After Iteration 3:**

Input: `[30, 40, 50]`
Output: `60`

---

### Final Result

After all iterations, `X` and `y` will be:

```
X = [
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
]

y = [
    40,
    50,
    60
]
```

---

### Visual Explanation: The Sliding Window

Imagine a window of size `window_size` (which is 3) moving over your data:

**Window 1:**
`[10 20 30]` 40 50 60

*   **Input (X):** `[10, 20, 30]`
*   **Output (y):** `40`

**Window 2:**
10 `[20 30 40]` 50 60

*   **Input (X):** `[20, 30, 40]`
*   **Output (y):** `50`

**Window 3:**
10 20 `[30 40 50]` 60

*   **Input (X):** `[30, 40, 50]`
*   **Output (y):** `60`

---

### Why do we use `i + window_size` for `y`?

The goal of this data preparation is to create sequences where a model learns to predict the _next_ value in the sequence given the _previous_ `window_size` values. Therefore:

*   The first `window_size` values (`data[i:i+window_size]`) form the input sequence (`X`).
*   The value immediately following this sequence (`data[i+window_size]`) is the target output (`y`) that the model should predict.

This technique is commonly known as a **sliding window** or **lagged features** approach, and it's a standard way to prepare sequential data for time series forecasting or sequence prediction tasks with models like LSTMs.

---

### Practice Exercise

Try changing `window_size = 2`.

What do you think `X` and `y` will become? Try predicting the answer yourself before running the code. It's a great way to check whether you've understood how the sliding window works!

#Step 6: Convert into NumPy Arrays

In [7]:
X = np.array(X)
y = np.array(y)

In [8]:
print("Input:")
print(X)

print()

print("Output:")
print(y)

Input:
[[10 20 30]
 [20 30 40]
 [30 40 50]]

Output:
[40 50 60]


In [9]:
print(X.shape)

(3, 3)


In [10]:
X = X.reshape((X.shape[0], X.shape[1], 1))

In [11]:
print(X.shape)

(3, 3, 1)


Understanding (3,3,1)
Samples = 3

There are 3 training examples.

Sample 1

10 20 30

↓

40
Sample 2

20 30 40

↓

50
Sample 3

30 40 50

↓

60