<a href="https://colab.research.google.com/github/faisu6339-glitch/Deep-Learning/blob/main/Padding_%26_Strides.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Padding and Strides in Deep Learning

Padding and strides are fundamental concepts in convolutional neural networks (CNNs), which are widely used in deep learning, especially for image processing. They control how the convolutional filter (or kernel) moves across the input and how the output feature map is shaped.

### **Padding**

Padding involves adding extra rows and columns of zeros (or sometimes other values) around the border of the input image or feature map before applying the convolution. There are two main types of padding:

1.  **'Valid' Padding (No Padding):**
    *   In this mode, no padding is added to the input. The convolution operation is applied only to the valid regions of the input, meaning the filter only moves to positions where it completely overlaps with the input data. This often results in an output feature map that is smaller than the input.
    *   **Effect:** Reduces the spatial dimensions of the output. Pixels at the edges of the input are processed fewer times than central pixels, potentially losing information at the boundaries.

2.  **'Same' Padding (Zero Padding):**
    *   In this mode, zeros are added symmetrically to the input so that the output feature map has the *same spatial dimensions* as the input. The amount of padding required depends on the filter size and stride.
    *   **Effect:** Preserves the spatial dimensions of the output. This is particularly useful for building deeper networks, as it prevents the feature maps from shrinking too rapidly. It also ensures that information at the edges of the input contributes equally to the output.
    *   **Example:** If you have a 3x3 filter and you want the output to be the same size as the input, you'd typically add 1 row/column of zeros around the border (padding = 1).

### **Strides**

Strides define the step size or the number of pixels the convolutional filter shifts across the input image or feature map. By default, the stride is usually 1, meaning the filter moves one pixel at a time.

*   **Stride = 1:** The filter moves one pixel at a time horizontally and vertically. This results in an output feature map that is slightly smaller than the input (if no padding is used) or the same size (if 'same' padding is used).

*   **Stride > 1 (e.g., Stride = 2):** The filter moves multiple pixels at a time (e.g., two pixels horizontally and two pixels vertically). This causes the filter to "skip" some pixels, effectively down-sampling the input and reducing the spatial dimensions of the output feature map.
    *   **Effect:** Significantly reduces the spatial dimensions of the output feature map, which helps in reducing computational cost and controlling overfitting by reducing the number of parameters.
    *   **Use Cases:** Often used in lieu of or in conjunction with pooling layers (like max pooling) to downsample the feature maps.

### **How They Work Together**

Padding and strides are often used in combination to achieve desired output sizes and control the computational complexity of the network:

*   **Padding to preserve information:** Padding, especially 'same' padding, ensures that edge information is not lost and helps maintain the spatial dimensions of feature maps through multiple convolutional layers.
*   **Strides to reduce dimensions:** Strides greater than 1 are used to effectively downsample the input, reducing the resolution of the feature maps and the computational burden. This is crucial for creating networks that can process high-resolution inputs efficiently and learn hierarchical features.

**In summary:**

*   **Padding** controls the size of the output feature map and how edge information is handled.
*   **Strides** control how much the filter moves at each step, influencing the downsampling of the input and the size of the output feature map.

By carefully selecting padding and stride values, deep learning practitioners can design CNN architectures that effectively extract features and maintain appropriate spatial resolutions throughout the network.

### Code Example: Padding and Strides with Keras (TensorFlow)

This example will use `tf.keras.layers.Conv2D` to show the effects of different padding and stride settings on an input tensor.

In [ ]:
import tensorflow as tf
import numpy as np

# Input tensor: 1 image, 5x5 pixels, 1 channel
# Represents a simple grayscale image
input_tensor = tf.constant(np.arange(1, 26).reshape(1, 5, 5, 1), dtype=tf.float32)
print("Input Tensor (5x5):\n", input_tensor.numpy().squeeze())

# --- Example 1: No Padding ('valid'), Stride 1 ---
print("\n--- Example 1: 'Valid' Padding, Stride 1 ---")
conv_valid_s1 = tf.keras.layers.Conv2D(
    filters=1, kernel_size=(3, 3), strides=(1, 1), padding='valid',
    kernel_initializer=tf.constant_initializer(np.ones((3,3,1,1))), use_bias=False
)
output_valid_s1 = conv_valid_s1(input_tensor)
print("Output Shape ('valid', stride 1):", output_valid_s1.shape)
print("Output ('valid', stride 1):\n", output_valid_s1.numpy().squeeze())

# --- Example 2: 'Same' Padding, Stride 1 ---
print("\n--- Example 2: 'Same' Padding, Stride 1 ---")
conv_same_s1 = tf.keras.layers.Conv2D(
    filters=1, kernel_size=(3, 3), strides=(1, 1), padding='same',
    kernel_initializer=tf.constant_initializer(np.ones((3,3,1,1))), use_bias=False
)
output_same_s1 = conv_same_s1(input_tensor)
print("Output Shape ('same', stride 1):", output_same_s1.shape)
print("Output ('same', stride 1):\n", output_same_s1.numpy().squeeze())

# --- Example 3: 'Valid' Padding, Stride 2 ---
print("\n--- Example 3: 'Valid' Padding, Stride 2 ---")
conv_valid_s2 = tf.keras.layers.Conv2D(
    filters=1, kernel_size=(3, 3), strides=(2, 2), padding='valid',
    kernel_initializer=tf.constant_initializer(np.ones((3,3,1,1))), use_bias=False
)
output_valid_s2 = conv_valid_s2(input_tensor)
print("Output Shape ('valid', stride 2):", output_valid_s2.shape)
print("Output ('valid', stride 2):\n", output_valid_s2.numpy().squeeze())

# --- Example 4: 'Same' Padding, Stride 2 ---
print("\n--- Example 4: 'Same' Padding, Stride 2 ---")
conv_same_s2 = tf.keras.layers.Conv2D(
    filters=1, kernel_size=(3, 3), strides=(2, 2), padding='same',
    kernel_initializer=tf.constant_initializer(np.ones((3,3,1,1))), use_bias=False
)
output_same_s2 = conv_same_s2(input_tensor)
print("Output Shape ('same', stride 2):", output_same_s2.shape)
print("Output ('same', stride 2):\n", output_same_s2.numpy().squeeze())


Input Tensor (5x5):
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]

--- Example 1: 'Valid' Padding, Stride 1 ---
Output Shape ('valid', stride 1): (1, 3, 3, 1)
Output ('valid', stride 1):
 [[ 63.  72.  81.]
 [108. 117. 126.]
 [153. 162. 171.]]

--- Example 2: 'Same' Padding, Stride 1 ---
Output Shape ('same', stride 1): (1, 5, 5, 1)
Output ('same', stride 1):
 [[ 16.  27.  33.  39.  28.]
 [ 39.  63.  72.  81.  57.]
 [ 69. 108. 117. 126.  87.]
 [ 99. 153. 162. 171. 117.]
 [ 76. 117. 123. 129.  88.]]

--- Example 3: 'Valid' Padding, Stride 2 ---
Output Shape ('valid', stride 2): (1, 2, 2, 1)
Output ('valid', stride 2):
 [[ 63.  81.]
 [153. 171.]]

--- Example 4: 'Same' Padding, Stride 2 ---
Output Shape ('same', stride 2): (1, 3, 3, 1)
Output ('same', stride 2):
 [[ 16.  33.  28.]
 [ 69. 117.  87.]
 [ 76. 123.  88.]]


### Code Example: Padding and Strides with PyTorch

This example will use `torch.nn.Conv2d` to show the effects of different padding and stride settings on an input tensor.

In [ ]:
import torch
import torch.nn as nn
import numpy as np

# Input tensor: 1 image, 1 channel, 5x5 pixels
# PyTorch typically uses (N, C, H, W) format
input_tensor_pt = torch.tensor(np.arange(1, 26).reshape(1, 1, 5, 5), dtype=torch.float32)
print("Input Tensor (1x1x5x5):\n", input_tensor_pt.squeeze().numpy())

# Define a 3x3 kernel with all ones for simplicity
kernel = torch.ones(1, 1, 3, 3)

# --- Example 1: No Padding (padding=0), Stride 1 ---
print("\n--- Example 1: Padding 0, Stride 1 ---")
conv_p0_s1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0, bias=False)
conv_p0_s1.weight = nn.Parameter(kernel)
output_p0_s1 = conv_p0_s1(input_tensor_pt)
print("Output Shape (padding 0, stride 1):", output_p0_s1.shape)
print("Output (padding 0, stride 1):\n", output_p0_s1.squeeze().detach().numpy())

# --- Example 2: Padding 1 (to achieve 'same' effect with 3x3 kernel), Stride 1 ---
print("\n--- Example 2: Padding 1, Stride 1 (equivalent to 'same' for 3x3 kernel) ---")
conv_p1_s1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=1, bias=False)
conv_p1_s1.weight = nn.Parameter(kernel)
output_p1_s1 = conv_p1_s1(input_tensor_pt)
print("Output Shape (padding 1, stride 1):", output_p1_s1.shape)
print("Output (padding 1, stride 1):\n", output_p1_s1.squeeze().detach().numpy())

# --- Example 3: Padding 0, Stride 2 ---
print("\n--- Example 3: Padding 0, Stride 2 ---")
conv_p0_s2 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0, bias=False)
conv_p0_s2.weight = nn.Parameter(kernel)
output_p0_s2 = conv_p0_s2(input_tensor_pt)
print("Output Shape (padding 0, stride 2):", output_p0_s2.shape)
print("Output (padding 0, stride 2):\n", output_p0_s2.squeeze().detach().numpy())

# --- Example 4: Padding 1, Stride 2 ---
print("\n--- Example 4: Padding 1, Stride 2 ---")
conv_p1_s2 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, bias=False)
conv_p1_s2.weight = nn.Parameter(kernel)
output_p1_s2 = conv_p1_s2(input_tensor_pt)
print("Output Shape (padding 1, stride 2):", output_p1_s2.shape)
print("Output (padding 1, stride 2):\n", output_p1_s2.squeeze().detach().numpy())


Input Tensor (1x1x5x5):
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]

--- Example 1: Padding 0, Stride 1 ---
Output Shape (padding 0, stride 1): torch.Size([1, 1, 3, 3])
Output (padding 0, stride 1):
 [[ 63.  72.  81.]
 [108. 117. 126.]
 [153. 162. 171.]]

--- Example 2: Padding 1, Stride 1 (equivalent to 'same' for 3x3 kernel) ---
Output Shape (padding 1, stride 1): torch.Size([1, 1, 5, 5])
Output (padding 1, stride 1):
 [[ 16.  27.  33.  39.  28.]
 [ 39.  63.  72.  81.  57.]
 [ 69. 108. 117. 126.  87.]
 [ 99. 153. 162. 171. 117.]
 [ 76. 117. 123. 129.  88.]]

--- Example 3: Padding 0, Stride 2 ---
Output Shape (padding 0, stride 2): torch.Size([1, 1, 2, 2])
Output (padding 0, stride 2):
 [[ 63.  81.]
 [153. 171.]]

--- Example 4: Padding 1, Stride 2 ---
Output Shape (padding 1, stride 2): torch.Size([1, 1, 3, 3])
Output (padding 1, stride 2):
 [[ 16.  33.  28.]
 [ 69. 117.  87.]
 [ 76. 123.  88.]]
