<a href="https://colab.research.google.com/github/faisu6339-glitch/Deep-Learning/blob/main/RNN_for_Sequence_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#RNN for Sequence Prediction

#Goal

Train an RNN to learn

10 20 30 → 40
20 30 40 → 50
30 40 50 → 60
40 50 60 → 70
50 60 70 → 80
60 70 80 → 90
70 80 90 → 100

Later we'll test it using

80 90 100 → ?
Expected = 110

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

In [40]:
X=np.array([
    [10,20,30],
    [20,30,40],
    [30,40,50],
    [40,50,60],
    [50,60,70],
    [60,70,80],
    [70,80,90]
])
y=np.array([
    40,
    50,
    60,
    70,
    80,
    90,
    100
])

In [41]:
print(X)
print(y)
print(X.shape)
print(y.shape)

[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]
 [70 80 90]]
[ 40  50  60  70  80  90 100]
(7, 3)
(7,)


#Normalize Data

In [42]:
X = X / 100
y = y / 100

In [43]:
print(X)
print(y)

[[0.1 0.2 0.3]
 [0.2 0.3 0.4]
 [0.3 0.4 0.5]
 [0.4 0.5 0.6]
 [0.5 0.6 0.7]
 [0.6 0.7 0.8]
 [0.7 0.8 0.9]]
[0.4 0.5 0.6 0.7 0.8 0.9 1. ]


#Reshape for RNN

#RNN expects data in

(samples,
 timesteps,
 features)

Currently

(7,3)

Convert into

(7,3,1)
X = X.reshape((X.shape[0], X.shape[1], 1))

print(X.shape)

Output

(8,3,1)

Meaning::

a)8 samples,

Each sample has::

b)3 time steps,

Each timestep has::

d)1 feature

In [44]:
X=X.reshape((X.shape[0], X.shape[1], 1))
print(X.shape)

(7, 3, 1)


#Build RNN Model

In [45]:
model=Sequential()
model.add(SimpleRNN(50,activation='tanh',input_shape=(3,1)))
model.add(Dense(1))
model.summary()


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_3 (SimpleRNN)        │ (None, 50)             │         2,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,651 (10.36 KB)

 Trainable params: 2,651 (10.36 KB)

 Non-trainable params: 0 (0.00 B)

#Explanation

SimpleRNN(20)

20 neurons

activation='tanh'

input_shape=(3,1)

3 timesteps

1 feature

#Dense layer

Predicts one number

#Compile Model

In [46]:
model.compile(
    optimizer='adam',
    loss='mse'
)


In [47]:
model.fit(
    X,
    y,
    epochs=500,
    verbose=1
)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.0923
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0465
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0170
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0037
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0042
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0124
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0205
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0236
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0214
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0161
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0100
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0051
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0024
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0020
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0033
Epoch 16/500
1/1 ━━━━

# Predict New Sequence

We know

80 90 100

Next should be

110

In [48]:
test=np.array([80,90,100])
test=test/100
test=test.reshape((1,3,1))

In [49]:
prediction = model.predict(test)

print("Predicted :", prediction[0][0]*100)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step
Predicted : 107.41136
