<a href="https://colab.research.google.com/github/faisu6339-glitch/Deep-Learning/blob/main/RNN_for_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Recurrent Neural Networks (RNNs) for NLP in Deep Learning

Recurrent Neural Networks (RNNs) are a class of neural networks particularly well-suited for processing sequential data, like natural language. Unlike traditional neural networks, RNNs have internal memory that allows them to process sequences of arbitrary length by maintaining a hidden state that captures information about previous elements in the sequence.

Here's a breakdown of how RNNs work for Natural Language Processing (NLP):

1.  **Sequential Processing**: In NLP, words in a sentence or characters in a word form a sequence. RNNs process this sequence one element (e.g., one word) at a time. As they process each word, they update their internal state.

2.  **Hidden State**: The core of an RNN is its hidden state (or hidden unit). This state acts like a memory, encapsulating information learned from all previous inputs in the sequence. At each time step, the RNN takes the current input and the previous hidden state to compute a new hidden state.

3.  **Weight Sharing**: The same set of weights is used across all time steps. This is crucial for learning patterns that occur at different positions in a sequence and makes the network efficient for variable-length inputs.

4.  **Output**: At each time step, the RNN can produce an output based on the current input and the hidden state. For NLP tasks, this output could be:
    *   **Per-word predictions**: Like in a language model, predicting the next word in a sequence.
    *   **Sequence-to-sequence tasks**: Where the entire input sequence is processed to generate an entire output sequence (e.g., machine translation, where an input sentence in one language is translated into an output sentence in another).
    *   **Sequence classification**: Where the entire input sequence is processed to produce a single output (e.g., sentiment analysis, classifying a movie review as positive or negative).

5.  **Backpropagation Through Time (BPTT)**: RNNs are trained using a variation of backpropagation called Backpropagation Through Time. This involves unfolding the network across time steps and then applying standard backpropagation. However, BPTT can suffer from vanishing or exploding gradient problems, especially for long sequences.

6.  **Variations**: To address the limitations of simple RNNs (like vanishing gradients), more advanced architectures have been developed, such as:
    *   **Long Short-Term Memory (LSTM) networks**: Introduce gating mechanisms to control the flow of information, allowing them to capture long-range dependencies more effectively.
    *   **Gated Recurrent Units (GRUs)**: A simpler alternative to LSTMs that also address the vanishing gradient problem with fewer parameters.

In [1]:
sentences = [
    "i love deep learning",
    "rnn is powerful",
    "nlp is interesting"
]

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

print(tokenizer.word_index)

{'is': 1, 'i': 2, 'love': 3, 'deep': 4, 'learning': 5, 'rnn': 6, 'powerful': 7, 'nlp': 8, 'interesting': 9}


In [3]:
sequences = tokenizer.texts_to_sequences(sentences)

print(sequences)

[[2, 3, 4, 5], [6, 1, 7], [8, 1, 9]]


In [4]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X = pad_sequences(
    sequences,
    maxlen=5,
    padding='post'
)

print(X)

[[2 3 4 5 0]
 [6 1 7 0 0]
 [8 1 9 0 0]]


In [5]:
X.shape = (3,5)

In [6]:
import numpy as np

y = np.array([1,0,1])

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Embedding, SimpleRNN, Dense

vocab_size = len(tokenizer.word_index) + 1

model = Sequential([
    Input(shape=(5,)),
    Embedding(
        input_dim=vocab_size,
        output_dim=32
    ),
    SimpleRNN(64),
    Dense(1, activation='sigmoid')
])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 5, 32)          │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 64)             │         6,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,593 (25.75 KB)

 Trainable params: 6,593 (25.75 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
Embedding(vocab_size,32)

<Embedding name=embedding_1, built=False>

In [9]:
Dense(1, activation='sigmoid')

<Dense name=dense_1, built=False>

In [10]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X, y, epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.6667 - loss: 0.6909
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.6649
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.6395
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6667 - loss: 0.6142
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.5887
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6667 - loss: 0.5627
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.5360
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6667 - loss: 0.5086
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.4806
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.4519


In [11]:
test_text = ["i love nlp"]

seq = tokenizer.texts_to_sequences(test_text)

seq = pad_sequences(seq, maxlen=5, padding='post')

pred = model.predict(seq)

print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step
[[0.74551016]]
